/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Create_gameRouteImport } from './routes/create_game'
import { Route as IndexRouteImport } from './routes/index'

const Create_gameRoute = Create_gameRouteImport.update({
  id: '/create_game',
  path: '/create_game',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create_game': typeof Create_gameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create_game': typeof Create_gameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create_game': typeof Create_gameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create_game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create_game'
  id: '__root__' | '/' | '/create_game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Create_gameRoute: typeof Create_gameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/create_game': {
      id: '/create_game'
      path: '/create_game'
      fullPath: '/create_game'
      preLoaderRoute: typeof Create_gameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Create_gameRoute: Create_gameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
